baseURL = "https://www.esamir.com/"
title = "csgeek Blog"
theme = "hugo-coder"
languageCode = "en-us"
languagecode = "en"
defaultcontentlanguage = "en"
googleAnalytics = "UA-46486821-1"
include_toc = true

paginate = 20
canonifyurls = true

pygmentsstyle = "fruity"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "esamir"
publishDir = "public"
enableRobotsTXT = "true"


[outputs]
  home = [ "HTML", "JSON" ]

[params]
    author = "Samir Faci (csgeek)"
    info = "Backend Engineer, Docker enthusiast and other musings"
    description = "csgeek's personal website"
    keywords = "blog,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    gravatar = "samir@esamir.com"
    footercontent = "Geeky musings, thoughts and other randomness"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/safaci2000/tree/"

    rtl = false

    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/safaci2000"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/csgeek/"
[[params.social]]
    name = "Mastodon"
    icon = "fab fa-mastodon fa-2x"
    weight = 1
    url = "https://mastodon.social/@csgeek"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram fa-2x"
    weight = 1
    url = "https://t.me/csgeek"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-exchange fa-2x"
    weight = 1
    url = "https://stackoverflow.com/users/669378/csgeek"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/samirfaci/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "posts/"

            [[languages.en.menu.main]]
            name = "About"
            weight = 2
            url = "about/"

            [[languages.en.menu.main]]
            name = "Search"
            weight = 3
            url = "search"
            
            [[languages.en.menu.main]]
            name = "Source"
            weight = 9
            identifier = "GitHub"
            url = "https://github.com/safaci2000/blog"

            [permalinks]
               posts = "/:06/:1/:2/:title/"

